#pragma config(Sensor, in1,    pot_cap,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  enc_fw,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  enc_drive,      sensorQuadEncoder)
#pragma config(Motor,  port1,           intake_cap,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           drive_r1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           drive_r2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           drive_r3,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           drive_l1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           drive_l2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           drive_l3,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           flywheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lift,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          intake_ball,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	SensorValue[enc_fw] = 0;
	SensorValue[enc_drive] = 0;
	SensorValue[pot_cap] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	//start moving forward
	motor[drive_l1] = motor[drive_l2] = motor[drive_l3] = -100;
	motor[drive_r1] = motor[drive_r2] = motor[drive_r3] = -100;
	
	//keep moving forward for 2500 ms
	wait(2500);
	
	//stop moving forward
	motor[drive_l1] = motor[drive_l2] = motor[drive_l3] = 0;
	motor[drive_r1] = motor[drive_r2] = motor[drive_r3] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
float rpm(){
	SensorValue[enc_fw] = 0;
	wait1Msec(100);

	float curr = SensorValue[enc_fw];
	float rpm = (curr / 1.666667) * 5;

	return rpm;
}

task usercontrol()
{
	motor[flywheel] = 40;
	int target = 0;
	while (true)
	{
		//tank drive
		motor[drive_r1] = motor[drive_r2] = motor[drive_r3] = vexRT[Ch2];
		motor[drive_l1] = motor[drive_l2] = motor[drive_l3] = vexRT[Ch3];

		//bang bang control for flywheel
		if(rpm() < target){
			motor[flywheel] = 70;
		}
		else
		{
			motor[flywheel] = 50;
		}

		//joystick controls for other motors
		if(vexRT[Btn5U]){
			motor[lift] = 127;
		}
		else if(vexRT[Btn5D]){
			motor[lift] = -127;
		}
		else{
			motor[lift] = 0;
		}

		if(vexRT[Btn6U]){
			motor[intake_ball] = 100;
		}
		else if(vexRT[Btn6D]){
			motor[intake_ball] = -100;
		}
		else{
			motor[intake_ball] = 0;
		}

		if(vexRT[Btn8U]){
			target = 1100;
		}
		else if(vexRT[Btn8D]){
			target = 400;
		}

		if(vexRT[Btn7L]){
			motor[intake_cap] = -60;
		}
		else if(vexRT[Btn7R]){
			motor[intake_cap] = 60;
		}
		else{
			motor[intake_cap] = 0;
		}
	}
}
