#pragma config(Sensor, dgtl1,  enc,            sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[enc] = 0;
	float lastError = 0;
	int target = 800;

	float kp = 0.1;
	float kd = 0.0;
	float ki = 0.0;

	while(){
		while(rpm() <= target){
			error = target - rpm();
			float calcP = error * kp;
			float calcD = (error - lastError) * kd;
			float calcI = (


}
