#pragma config(Sensor, dgtl1,  enc,            sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float rpm(){
	wait1Msec(100);

	float curr = SensorValue[enc];
	float rpm = (curr / 1.66667) * 5;
	//writeDebugStreamLine("%f", rpm);
	
	return rpm;
}

task main()
{
	SensorValue[enc] = 0;
	float output = 0;
	float error = 0;
	float error_last = 0;
	int target = 800;

	float kp = 0.5;
	float kd = 0;
	float ki = 0;

	while(){
		while(rpm() != target){
			error = target - rpm();
			float calc_P = error * kp;
			float calc_D = (error - error_last) * kd;
			float calc_I = (error + error_last) * ki;
			
			output = calc_P + calc_D + calc_I;

			motor[port4] = -output;
			motor[port5] =  output;
			
			wait10Msec(10);
			writeDebugStreamLine("int x is: %d", error);
		}
	}
}
